# Default values for todo-ai-project.

frontend:
  replicaCount: 1
  image:
    repository: todo-frontend  # <--- Sirf image ka naam
    pullPolicy: Never
    tag: v2
  service:
    type: NodePort
    port: 3000

backend:
  replicaCount: 1
  image:
    repository: todo-backend   
    pullPolicy: Never
    tag: "latest"
  service:
    type: ClusterIP
    port: 8000